services:
  db:
    image: postgres:13.10
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - microservices_network

  redis:
    image: redis:7.0
    env_file: .env
    ports:
      - 6379:6379
    volumes:
      - ./redisdata:/data
    networks:
      - microservices_network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
    env_file: .env
    networks:
      - microservices_network

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - 9092:9092
    env_file: .env
    depends_on:
      - zookeeper
    networks:
      - microservices_network

  fastapi_service:
    build: ./fastapi_service/
    ports:
      - 9000:8000
    depends_on:
      - db
      - redis
      - kafka
    networks:
      - microservices_network
    develop:
      watch:
        - action: sync+restart
          path: ./fastapi_service
          target: /app/

  django_service:
    build: ./django_service/
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
      - fastapi_service
      - kafka
    networks:
      - microservices_network

volumes:
  pg_data:

networks:
  microservices_network: